#!/bin/bash
set -e
set -o pipefail

export INSTALLDIR=`echo ~`
export ARCHITECTURE_PATH=`./architecture-path`
export QARCHITECTURE_PATH=`./architecture-path`
export INSTALLLIB=${INSTALLDIR}/lib
export INSTALLLIBA=${INSTALLLIB}/${ARCHITECTURE_PATH}
export INSTALLBIN=${INSTALLDIR}/bin
export INSTALLBINA=${INSTALLBIN}/${ARCHITECTURE_PATH}
export INSTALLINCLUDE=${INSTALLDIR}/include
export INSTALLINCLUDEA=${INSTALLINCLUDE}/${ARCHITECTURE_PATH}
export LD_LIBRARY_PATH=${INSTALLLIBA}:${LD_LIBRARY_PATH}
export PATH=${PATH}:${HOME}/bin/`./architecture-path`

# TODO Check architecture path is x86_64-Debian

./install-amd64
source ~/.bashrc
tar xvf QobiScheme.tar.Z
pushd QobiScheme-1.46/source
cp ../../QobiScheme-makefile makefile
make port
cd ${ARCHITECTURE_PATH}
make install -j10
cd ..
# rm -rf `architecture-path`

