#!/bin/bash
set -e
set -o pipefail

sudo ./packages.sh

./build-amd64
source ~/.bashrc
cp -r darpa-collaboration ~/
~/darpa-collaboration/bin/build-architecture-libs
~/darpa-collaboration/bin/install-ffmpeg-presets
tar -C ${HOME}/darpa-collaboration/pkg -xvf irobot_libcudafelz_1.3_alpha_toolkit_3.2_64bit.tar.gz
~/darpa-collaboration/bin/build-opencv.sh
~/darpa-collaboration/bin/build-flowlib.sh
~/darpa-collaboration/bin/build-cudaklt.sh
cp ~/darpa-collaboration/bin/darpa-wrap ~/bin/
pushd ~/darpa-collaboration/ffmpeg
darpa-wrap make ffmpeg ffmpeg-bindings
darpa-wrap make install
popd
popd
pushd ~/darpa-collaboration/ideas
make port
cd `architecture-path`
darpa-wrap make dsci video-to-sentences render-darpa-stuff -j10
popd

echo "Running example video"
darpa-wrap ~/darpa-collaboration/ideas/x86_64-Debian/video-to-sentences -write-object-detector -t 12 -cuda-object-detector -1 -0.1 0.6 -cuda-klt -cuda-optical-flow -look-ahead 2 -model-path ~/darpa-collaboration/voc4-models/ -verbose -event-models-file ~/darpa-collaboration/event-hmms/event-models.text -m person,person-down,person-crouch ~/video-to-sentences-h21jan2012/Chase1_A1_C1_Act1_4_PARK1_ML_MIDD_DARK_4433d840-c5af-11df-bed3-e80688cb869a
